// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrgenceTech.Data;

#nullable disable

namespace UrgenceTech.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515021328_AjouterDateCreation")]
    partial class AjouterDateCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("UrgenceTech.Models.Urgence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilisateurID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UtilisateurID");

                    b.ToTable("Urgences");
                });

            modelBuilder.Entity("UrgenceTech.Models.Utilisateur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateVerrouillage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TentativesEchouees")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Courriel = "admin@urgencetech.com",
                            DateCreation = new DateTime(2026, 5, 14, 22, 13, 28, 653, DateTimeKind.Local).AddTicks(2875),
                            MotDePasse = "$2a$11$w8j5zFfQT.956188WWkAM.UPNYsP2vfKxtXBSSRrkjtq2NVe64CVe",
                            NomComplet = "Admin Test",
                            Role = "Administrateur",
                            Status = true,
                            TentativesEchouees = 0
                        });
                });

            modelBuilder.Entity("UrgenceTech.Models.Urgence", b =>
                {
                    b.HasOne("UrgenceTech.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
