// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrgenceTech.Data;

#nullable disable

namespace UrgenceTech.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413035104_AjouterVerrouillage")]
    partial class AjouterVerrouillage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("UrgenceTech.Models.Utilisateur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateVerrouillage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TentativesEchouees")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Courriel = "admin@urgencetech.com",
                            MotDePasse = "admin123",
                            NomComplet = "Admin Test",
                            Role = "Administrateur",
                            Status = true,
                            TentativesEchouees = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
