// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrgenceTech.Data;

#nullable disable

namespace UrgenceTech.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("UrgenceTech.Models.Urgence", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilisateurID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UtilisateurID");

                    b.ToTable("Urgences");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DateCreation = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patient de 65 ans",
                            Priorite = "Critique",
                            Statut = "Ouverte",
                            Titre = "Patient en arrêt cardiaque",
                            UtilisateurID = 1
                        },
                        new
                        {
                            ID = 2,
                            DateCreation = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patient de 25 ans",
                            Priorite = "Moyenne",
                            Statut = "En cours",
                            Titre = "Fracture du bras",
                            UtilisateurID = 1
                        },
                        new
                        {
                            ID = 3,
                            DateCreation = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patient de 10 ans",
                            Priorite = "Haute",
                            Statut = "Résolue",
                            Titre = "Allergie alimentaire",
                            UtilisateurID = 1
                        });
                });

            modelBuilder.Entity("UrgenceTech.Models.Utilisateur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateVerrouillage")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TentativesEchouees")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Courriel = "admin@urgencetech.com",
                            DateCreation = new DateTime(2026, 5, 14, 22, 13, 28, 653, DateTimeKind.Local).AddTicks(2875),
                            MotDePasse = "$2a$11$/tdtO3tuFuyHRESnyv5nt.2LvVMotgUJ/bKg723svIPhFIb4CLdma",
                            NomComplet = "Admin Test",
                            Role = "Administrateur",
                            Status = true,
                            TentativesEchouees = 0
                        });
                });

            modelBuilder.Entity("UrgenceTech.Models.Urgence", b =>
                {
                    b.HasOne("UrgenceTech.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
